// Static seed data for Solution Villa website

export const services = [
  {
    id: 1,
    icon: "Palette",
    title: "Branding & Design",
    description: "We craft compelling brand identities that resonate with your audience — from logo design to complete visual systems that make you unforgettable.",
    tag: "Creative",
    color: "from-purple-500/20 to-primary/20",
  },
  {
    id: 2,
    icon: "TrendingUp",
    title: "Digital Marketing",
    description: "Data-driven campaigns across SEO, social media, PPC, and email marketing that deliver measurable ROI and sustainable growth.",
    tag: "Growth",
    color: "from-primary/20 to-cyan-500/20",
  },
  {
    id: 3,
    icon: "Video",
    title: "Event Production",
    description: "End-to-end event management and production — from intimate corporate gatherings to large-scale conferences and hybrid events.",
    tag: "Events",
    color: "from-red-500/20 to-orange-500/20",
  },
  {
    id: 4,
    icon: "Film",
    title: "Media & Content Creation",
    description: "Professional video production, photography, podcasts, and content strategies that captivate audiences and drive engagement.",
    tag: "Media",
    color: "from-pink-500/20 to-red-500/20",
  },
  {
    id: 5,
    icon: "Globe",
    title: "Website Development",
    description: "Modern, fast, and conversion-optimized websites built with cutting-edge technologies — from landing pages to complex web applications.",
    tag: "Web",
    color: "from-blue-500/20 to-primary/20",
  },
  {
    id: 6,
    icon: "Printer",
    title: "Printing & Branding",
    description: "High-quality print solutions including banners, flyers, business cards, branded merchandise, and large-format printing.",
    tag: "Print",
    color: "from-green-500/20 to-teal-500/20",
  },
  {
    id: 7,
    icon: "Briefcase",
    title: "Business Consulting",
    description: "Strategic business advisory services that help organizations optimize operations, enter new markets, and achieve sustainable growth.",
    tag: "Strategy",
    color: "from-yellow-500/20 to-orange-500/20",
  },
  {
    id: 8,
    icon: "Smartphone",
    title: "Mobile App Development",
    description: "Native and cross-platform mobile applications for iOS and Android that deliver exceptional user experiences and drive business value.",
    tag: "Mobile",
    color: "from-indigo-500/20 to-blue-500/20",
  },
  {
    id: 9,
    icon: "Code2",
    title: "Software Solutions",
    description: "Custom enterprise software, ERP systems, CRM platforms, and automation tools tailored to your unique business requirements.",
    tag: "Software",
    color: "from-cyan-500/20 to-teal-500/20",
  },
  {
    id: 10,
    icon: "Cloud",
    title: "Cloud Solutions",
    description: "Cloud infrastructure, migration services, DevOps implementation, and managed cloud services for scalable, secure operations.",
    tag: "Cloud",
    color: "from-sky-500/20 to-blue-500/20",
  },
];

export const stats = [
  { value: 200, suffix: "+", label: "Projects Completed" },
  { value: 150, suffix: "+", label: "Happy Clients" },
  { value: 50, suffix: "+", label: "Team Members" },
  { value: 8, suffix: "+", label: "Years of Experience" },
];

export const testimonials = [
  {
    id: 1,
    quote: "Solution Villa transformed our entire digital presence. Their team's expertise in branding and web development exceeded our expectations. We saw a 300% increase in online leads within just 3 months.",
    author_name: "Amara Okonkwo",
    author_title: "CEO",
    company: "TechBridge Africa",
    avatar_url: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop",
  },
  {
    id: 2,
    quote: "The mobile app they built for us is nothing short of outstanding. Clean UI, blazing fast performance, and delivered on time. Solution Villa is our go-to technology partner.",
    author_name: "Kweku Mensah",
    author_title: "Founder",
    company: "PayFast Ghana",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
  },
  {
    id: 3,
    quote: "Their digital marketing campaigns generated unprecedented results. Our social media engagement tripled and website traffic increased by 450%. Truly professional team.",
    author_name: "Zara Ibrahim",
    author_title: "Marketing Director",
    company: "Sahara Ventures",
    avatar_url: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&h=100&fit=crop",
  },
  {
    id: 4,
    quote: "Solution Villa organized our annual conference flawlessly. From concept to execution, every detail was perfect. The event production quality was world-class.",
    author_name: "Emmanuel Adeyemi",
    author_title: "Operations Manager",
    company: "Lagos Business Forum",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
  },
  {
    id: 5,
    quote: "The brand identity they created for us perfectly captures our vision. We get compliments every single day. Solution Villa truly understands modern African business.",
    author_name: "Fatima Al-Hassan",
    author_title: "Brand Manager",
    company: "AfriCraft Studios",
    avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop",
  },
];

export const portfolioItems = [
  {
    id: 1,
    title: "TechBridge Rebrand",
    category: "Branding",
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&h=400&fit=crop",
    client: "TechBridge Africa",
    description: "Complete brand identity redesign including logo, color system, and brand guidelines.",
  },
  {
    id: 2,
    title: "PayFast Mobile App",
    category: "Mobile Apps",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&h=800&fit=crop",
    client: "PayFast Ghana",
    description: "Cross-platform fintech application with real-time payments and analytics.",
  },
  {
    id: 3,
    title: "Sahara E-Commerce",
    category: "Websites",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=500&fit=crop",
    client: "Sahara Ventures",
    description: "High-converting e-commerce platform with custom checkout experience.",
  },
  {
    id: 4,
    title: "Lagos Forum 2024",
    category: "Events",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop",
    client: "Lagos Business Forum",
    description: "Annual business conference with 2,000+ attendees and live streaming.",
  },
  {
    id: 5,
    title: "AfriCraft Brand Film",
    category: "Media",
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=600&h=600&fit=crop",
    client: "AfriCraft Studios",
    description: "4K brand documentary showcasing artisan craftsmanship across West Africa.",
  },
  {
    id: 6,
    title: "HealthNet Dashboard",
    category: "Software",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop",
    client: "HealthNet Nigeria",
    description: "Hospital management system serving 15 facilities nationwide.",
  },
  {
    id: 7,
    title: "Harvest Packaging",
    category: "Printing",
    image: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=500&fit=crop",
    client: "Harvest Foods",
    description: "Premium product packaging and brand collateral for FMCG brand.",
  },
  {
    id: 8,
    title: "GrowAfrica Campaign",
    category: "Marketing",
    image: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&h=400&fit=crop",
    client: "GrowAfrica Fund",
    description: "Pan-African digital marketing campaign reaching 5M+ across 12 countries.",
  },
];

export const blogPosts = [
  {
    id: 1,
    slug: "future-of-digital-marketing-africa",
    title: "The Future of Digital Marketing in Africa: Trends for 2025",
    excerpt: "Africa's digital landscape is evolving rapidly. Discover the key trends that will define marketing strategy across the continent in the coming years.",
    category: "Digital Marketing",
    author: "Amara Osei",
    date: "June 5, 2025",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=600&h=400&fit=crop",
    featured: true,
  },
  {
    id: 2,
    slug: "building-brand-africa",
    title: "Building a World-Class Brand in Africa: A Strategic Guide",
    excerpt: "From Lagos to Nairobi, the most successful African brands share common traits. Here's what separates good brands from iconic ones.",
    category: "Branding",
    author: "Kwame Asante",
    date: "May 28, 2025",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=600&h=400&fit=crop",
    featured: false,
  },
  {
    id: 3,
    slug: "mobile-first-africa",
    title: "Why Mobile-First Is Not Optional for African Tech Companies",
    excerpt: "With mobile internet penetration at 65% and rising, African tech companies that don't prioritize mobile are leaving massive market share on the table.",
    category: "Technology",
    author: "Fatima Diallo",
    date: "May 15, 2025",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1556155092-490a1ba16284?w=600&h=400&fit=crop",
    featured: false,
  },
];

export const teamMembers = [
  {
    id: 1,
    name: "Victor Okafor",
    position: "Chief Executive Officer",
    department: "Leadership",
    bio: "15+ years in technology and business development across Africa. Passionate about driving digital transformation.",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 2,
    name: "Adaeze Nwosu",
    position: "Chief Creative Officer",
    department: "Design",
    bio: "Award-winning creative director with expertise in brand strategy and visual design for global and African markets.",
    photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 3,
    name: "Kofi Mensah",
    position: "CTO",
    department: "Technology",
    bio: "Full-stack engineer and architect with expertise in cloud infrastructure, mobile development, and enterprise software.",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 4,
    name: "Zainab Al-Amin",
    position: "Head of Digital Marketing",
    department: "Marketing",
    bio: "Performance marketing specialist who has managed campaigns across 20+ African countries with proven ROI track records.",
    photo: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 5,
    name: "Emeka Chukwu",
    position: "Head of Events",
    department: "Events",
    bio: "Seasoned event producer with 200+ events under his belt, from intimate boardroom sessions to stadium-scale productions.",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 6,
    name: "Amara Diallo",
    position: "Senior UX Designer",
    department: "Design",
    bio: "Human-centered design practitioner creating intuitive digital experiences that bridge technology and culture.",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 7,
    name: "Tunde Afolabi",
    position: "Lead Developer",
    department: "Technology",
    bio: "Backend architect specializing in scalable microservices, API design, and cloud-native applications.",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
  {
    id: 8,
    name: "Ngozi Eze",
    position: "Content Strategist",
    department: "Marketing",
    bio: "Storyteller and content expert who builds content ecosystems that attract, engage, and convert across all channels.",
    photo: "https://images.unsplash.com/photo-1598550880863-4e8aa3d0edb4?w=300&h=300&fit=crop",
    linkedin: "#",
    twitter: "#",
  },
];

export const caseStudies = [
  {
    id: 1,
    slug: "techbridge-digital-transformation",
    title: "TechBridge Africa: Complete Digital Transformation",
    client: "TechBridge Africa",
    industry: "Technology",
    cover: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
    problem: "TechBridge was struggling with an outdated brand, low digital visibility, and poor conversion rates despite having an excellent product.",
    solution: "We delivered a complete rebrand, new website, and integrated digital marketing strategy across all channels.",
    results: "300% increase in leads, 5x social media growth, 180% revenue increase in 6 months.",
    metric1: { value: "300%", label: "Lead Increase" },
    metric2: { value: "5x", label: "Social Growth" },
    metric3: { value: "180%", label: "Revenue Growth" },
  },
  {
    id: 2,
    slug: "payfast-mobile-fintech",
    title: "PayFast: Building Africa's Fastest Payment App",
    client: "PayFast Ghana",
    industry: "Fintech",
    cover: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=500&fit=crop",
    problem: "PayFast needed a secure, fast, and user-friendly mobile payment solution to compete in Ghana's growing fintech market.",
    solution: "We built a cross-platform app with biometric authentication, real-time transactions, and an intuitive UX in just 4 months.",
    results: "500K+ downloads in first year, 4.8 star rating, processing $2M+ daily transactions.",
    metric1: { value: "500K+", label: "Downloads" },
    metric2: { value: "4.8★", label: "App Rating" },
    metric3: { value: "$2M+", label: "Daily Volume" },
  },
  {
    id: 3,
    slug: "lagos-forum-event-production",
    title: "Lagos Business Forum: Flagship Event Production",
    client: "Lagos Business Forum",
    industry: "Events",
    cover: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&h=500&fit=crop",
    problem: "The Lagos Business Forum needed to elevate its annual conference to international standards while managing complex logistics for 2,000+ attendees.",
    solution: "Full event production including staging, AV, live streaming, mobile app for attendees, and post-event content package.",
    results: "2,200 attendees, 45 speakers, 15K live stream viewers, 98% satisfaction rate.",
    metric1: { value: "2,200", label: "Attendees" },
    metric2: { value: "15K", label: "Live Viewers" },
    metric3: { value: "98%", label: "Satisfaction" },
  },
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/case-studies", label: "Case Studies" },
  { href: "/blog", label: "Blog" },
  { href: "/contact", label: "Contact" },
];

export const footerLinks = {
  services: [
    { label: "Branding & Design", href: "/#services" },
    { label: "Digital Marketing", href: "/#services" },
    { label: "Website Development", href: "/#services" },
    { label: "Mobile Apps", href: "/#services" },
    { label: "Event Production", href: "/#services" },
    { label: "Cloud Solutions", href: "/#services" },
  ],
  company: [
    { label: "About Us", href: "/about" },
    { label: "Our Team", href: "/team" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Case Studies", href: "/case-studies" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  resources: [
    { label: "Privacy Policy", href: "#" },
    { label: "Terms of Service", href: "#" },
    { label: "Cookie Policy", href: "#" },
    { label: "Sitemap", href: "#" },
  ],
};
